from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd334fba090c8'
down_revision = '51cd242741c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=64), nullable=False))
        # Provide a name for the unique constraint
        batch_op.create_unique_constraint('uq_fs_uniquifier', ['fs_uniquifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Use the same name when dropping the constraint
        batch_op.drop_constraint('uq_fs_uniquifier', type_='unique')
        batch_op.drop_column('fs_uniquifier')

    # ### end Alembic commands ###
